# Generated by Django 3.0.5 on 2020-04-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statu', models.CharField(choices=[('w', 'await'), ('A', 'accepted'), ('D', 'denied')], default='W', max_length=1)),
                ('name', models.CharField(max_length=30)),
                ('event', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=5)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
