# Generated by Django 3.0.5 on 2020-04-20 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('await', 'Await'), ('process', 'Accepted'), ('denied', 'Denied')], default='await', max_length=10)),
                ('event', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=5)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('date_request', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
