# Generated by Django 3.0.5 on 2020-04-14 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='statu',
        ),
        migrations.AddField(
            model_name='request',
            name='statut',
            field=models.CharField(choices=[('await', 'Await'), ('process', 'Accepted'), ('denied', 'Denied')], default='await', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
