# Generated by Django 3.0.5 on 2020-04-21 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200421_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 13, 57, 54, 725596)),
        ),
    ]
