# Generated by Django 3.0.5 on 2020-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200413_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
