# Generated by Django 3.0.5 on 2020-04-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_request_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
