# Generated by Django 3.0.5 on 2020-04-21 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200421_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 14, 47, 7, 224336)),
        ),
    ]
