# Generated by Django 3.0.5 on 2020-04-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200413_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='notification',
        ),
    ]
