# Generated by Django 3.0.5 on 2020-04-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_auto_20200413_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date',
            new_name='date_ev',
        ),
    ]
