# Generated by Django 3.0.5 on 2020-04-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_auto_20200413_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='date_ev',
            new_name='date',
        ),
    ]
