# Generated by Django 3.0.5 on 2020-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200419_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static\\media\\default.jpg', upload_to='static/media'),
        ),
    ]
